name: Publish site

on:
  workflow_call:
    inputs:
      destination_dir:
        required: true
        type: string

jobs:
  publish-site:
    name: Publish site
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Deploy to `${{ inputs.destination_dir }}` directory of remote storage
        run: |
          echo ${{ env.AWS_BUCKET_NAME }}
          echo ${{ env.AWS_REGION }}
          echo ${{ env.AWS_ROLE_ARN }}
