name: Publish site

on:
  workflow_call:
    inputs:
      destination_dir:
        required: true
        type: string

jobs:
  publish-site:
    name: Publish site
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Ensure `destination_dir` is not empty
        if: ${{ inputs.destination_dir == '' }}
        run: exit 1
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: ghactionssession
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to `${{ inputs.destination_dir }}` directory of remote storage
        run: |
          echo ${{ env.AWS_ROLE_ARN }}
          echo ${{ env.AWS_REGION }}
          echo ${{ env.AWS_BUCKET_NAME }}/${{ inputs.destination_dir }}
