name: Publish Release

on:
  workflow_call:
    secrets:
      AWS_REGION:
        required: true
      AWS_ROLE_ARN:
        required: true
      AWS_BUCKET_NAME:
        required: true

jobs:
  publish-release-remote-storage:
    name: Publish release version des
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    uses: ./.github/workflows/publish-site.yml
    with:
      destination_dir: dest
