name: Publish Release

on:
  workflow_call:


jobs:
  publish-release-remote-storage:
    name: Publish release version des
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    uses: ./.github/workflows/publish-site.yml
    with:
      destination_dir: dest
